---
kernel: 
  version: 2.1.1
  required: true
  requirements: 
    liberty: 
      min: 2.1.7
    users: 
      min: 2.1.4
    themes: 
      min: 2.0.1
    languages: 
      min: 2.0.0
  description: The kernel manages configuraiton and operation of the cms
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
    url: http://www.gnu.org/copyleft/lesser.html 
  homeable: false
  tables: 
    adodb_logsql: |
      
      created T NOT NULL,
      sql0 C(250) NOTNULL,
      sql1 X NOTNULL,
      params X NOTNULL,
      tracer X NOTNULL,
      timer N(16.6) NOTNULL
      
    kernel_config: |
      
      config_name C(40) PRIMARY,
      package C(100),
      config_value C(250)
      
    mail_notifications: |
      
      event C(200),
      object C(200),
      email C(200)
      
    sessions: |
      
      sesskey C(32) PRIMARY,
      expiry I NOTNULL,
      expireref C(64),
      session_data X not null

    packages: |

      guid C(64) PRIMARY,
      version C(16) NOTNULL DEFAULT '0.0.0',
      homeable C(1) NOTNULL DEFAULT 'y',
      active C(1) DEFAULT NULL,
      required C(1) DEFAULT NULL,
      dir C(64) NOTNULL,
      name C(64),
      description C(250)

    package_plugins: |

      guid C(64) PRIMARY,
      package_guid C(64) NOTNULL,
      version C(16) NOTNULL DEFAULT '0.0.0',
      active C(1) DEFAULT NULL,
      required C(1) DEFAULT NULL,
      path_type C(64) NOTNULL,
      handler_file C(64) NOTNULL,
      name C(64),
      description C(250)
      CONSTRAINT '
      , CONSTRAINT `package_guid_ref` FOREIGN KEY (`package_guid`) REFERENCES `packages`( `guid` )'

    package_plugins_api_hooks: |
      api_hook C(64) PRIMARY,
      api_type C(64) PRIMARY

    package_plugins_api_map: |
      plugin_guid C(64) PRIMARY,
      api_hook C(64) PRIMARY,
      api_type C(64) PRIMARY,
      plugin_handler C(250) NOTNULL
      CONSTRAINT '
      , CONSTRAINT `plugin_guid_ref` FOREIGN KEY (`plugin_guid`) REFERENCES `package_plugins`( `guid` )
      , CONSTRAINT `plugin_api_hook_ref` FOREIGN KEY (`api_hook`,`api_type`) REFERENCES `package_plugins_api_hooks`( `api_hook`,`api_type` )'
      
  preferences: 
    site_online_help: y
    site_form_help: y
    site_short_date_format: %d %b %Y
    site_short_time_format: %H:%M %Z
    site_upload_dir: storage
    site_closed_msg: >
      Site is closed for maintainance; please
      come back later.
    site_http_port: 80
    site_http_prefix: /
    site_https_port: 443
    site_https_prefix: /
    users_count_admin_pageviews: y
    site_display_utc: UTC
    site_long_date_format: %A %d of %B, %Y
    site_long_time_format: %H:%M:%S %Z
    site_top_column: y
    site_right_column: y
    site_left_column: y
    site_bottom_column: y
    site_display_reltime: y
    max_records: 10
    language: en
    site_sender_email: 
    site_url_index: 
  permissions: 
    p_admin: 
      description: >
        Can manage users groups and permissions
        and all aspects of site management
      level: admin
    p_access_closed_site: 
      description: Can access site when closed
      level: admin
  modules:
    - pos: 5
      layout_area: t
      module_rsrc: bitpackage:kernel/mod_site_title.tpl
    - pos: 10
      layout_area: t
      module_rsrc: bitpackage:kernel/mod_top_menu.tpl
    - pos: 5
      layout_area: r
      module_rsrc: bitpackage:kernel/mod_package_menu.tpl
    - title: bitweaver
      pos: 10
      layout_area: r
      module_rsrc: bitpackage:kernel/mod_bitweaver_info.tpl
    - title: Server Statistics
      groups: Admin
      pos: 15
      layout_area: r
      module_rsrc: bitpackage:kernel/mod_server_stats.tpl
    - title: Powered by
      pos: 20
      layout_area: r
      module_rsrc: bitpackage:kernel/mod_powered_by.tpl
    - pos: 5
      layout_area: b
      module_rsrc: bitpackage:kernel/mod_bottom_bar.tpl
